### ISSUE TITLE
Fix Table name ICD-9 to ICD-10

### ISSUE THREAD

**Issue by argmonster** [txace/icd10-sql#1]
The file CreateTable-ICD-9-to-IDC-10-GEM.sql has this line:

CREATE TABLE [dbo].[t_ICD-10_ICD-10_with_GEM_AXIS]

should probably be

CREATE TABLE [dbo].[t_ICD-9_ICD-10_with_GEM_AXIS]

some what related:

the 10 -> 9 table has a column order of 9 then 10 
and the 9 -> 10 table has a column order of 10 then 9. Is that on purpose?

**Comment by rhwhaite** [comment]
The t_ICD-10 prefix on those tables is really an identifier for the ICD-10 project.  The next ICD reference indicates the starting point like ICD-9 or ICD-10.  The GEM stands for General Equivalence Mapping.

At least that’s what my sick mind was thinking as I was creating those tables.  I really didn’t want to confuse these new tables with any existing ICD-9 tables folks may have.

**Comment by argmonster** [comment]
That makes sense. Thanks
