### ISSUE TITLE
dst missing from dst import file

### ISSUE THREAD

**Issue by argmonster** [txace/icd10-sql#7]
c.dx10.stat is not part of the DX10DST.usc script, but it is declared by inc_DX10.usc and referenced in DX10.usc and CONVICD10_9.usc

Looks like it references a dct-2088, can an export of that dct be added to the project as well?

**Comment by rhwhaite** [comment]
c.dx10.stat has been added to the ICD10DST.usc script.  DCT 2088 as been exported and the export file has been added to the project.
